"""Add simple authentication support

Revision ID: 79b2254e8076
Revises: b61460598eb2
Create Date: 2025-10-02 17:13:03.801488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b2254e8076'
down_revision: Union[str, None] = 'b61460598eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simple_sessions_id'), 'simple_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_simple_sessions_session_id'), 'simple_sessions', ['session_id'], unique=True)
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.drop_index(op.f('ix_simple_sessions_session_id'), table_name='simple_sessions')
    op.drop_index(op.f('ix_simple_sessions_id'), table_name='simple_sessions')
    op.drop_table('simple_sessions')
    # ### end Alembic commands ###
