"""add_children_field_to_customer_profile

Revision ID: 8bcd32d4afae
Revises: 240c9283bdec
Create Date: 2025-10-03 15:39:35.997224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcd32d4afae'
down_revision: Union[str, None] = '240c9283bdec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with a default value for existing records
    op.add_column('customer_profiles', sa.Column('children', sa.String(length=3), nullable=False, server_default='No'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'children')
    # ### end Alembic commands ###
