"""Add consultation requests table

Revision ID: 5cd8640bba5d
Revises: 7917158dfb99
Create Date: 2025-11-15 21:14:31.734329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd8640bba5d'
down_revision: Union[str, None] = '7917158dfb99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=False),
    sa.Column('preferred_time', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consultation_created_at', 'consultation_requests', ['created_at'], unique=False)
    op.create_index('idx_consultation_email', 'consultation_requests', ['email'], unique=False)
    op.create_index('idx_consultation_source', 'consultation_requests', ['source'], unique=False)
    op.create_index('idx_consultation_status', 'consultation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_consultation_requests_email'), 'consultation_requests', ['email'], unique=False)
    op.create_index(op.f('ix_consultation_requests_id'), 'consultation_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_requests_id'), table_name='consultation_requests')
    op.drop_index(op.f('ix_consultation_requests_email'), table_name='consultation_requests')
    op.drop_index('idx_consultation_status', table_name='consultation_requests')
    op.drop_index('idx_consultation_source', table_name='consultation_requests')
    op.drop_index('idx_consultation_email', table_name='consultation_requests')
    op.drop_index('idx_consultation_created_at', table_name='consultation_requests')
    op.drop_table('consultation_requests')
    # ### end Alembic commands ###
