"""add_question_variation_mapping_back_to_company_trackers

Revision ID: b52a1a5a8503
Revises: 5cd8640bba5d
Create Date: 2025-11-16 01:58:27.906317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52a1a5a8503'
down_revision: Union[str, None] = '5cd8640bba5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_trackers', sa.Column('question_variation_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_trackers', 'question_variation_mapping')
    # ### end Alembic commands ###
