"""Add CompanyDetails and CompanyCustomerProfile models

Revision ID: 8be790779d0d
Revises: remove_arabic_periods
Create Date: 2025-12-16 15:47:27.245185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be790779d0d'
down_revision: Union[str, None] = 'remove_arabic_periods'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('company_trackers', sa.Column('enable_variations', sa.Boolean(), nullable=True))
    op.add_column('company_trackers', sa.Column('variations_enabled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('company_trackers', sa.Column('variations_enabled_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_trackers_enable_variations'), 'company_trackers', ['enable_variations'], unique=False)
    op.create_foreign_key(None, 'company_trackers', 'users', ['variations_enabled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_trackers', type_='foreignkey')
    op.drop_index(op.f('ix_company_trackers_enable_variations'), table_name='company_trackers')
    op.drop_column('company_trackers', 'variations_enabled_by')
    op.drop_column('company_trackers', 'variations_enabled_at')
    op.drop_column('company_trackers', 'enable_variations')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
