"""add_company_tracking_to_incomplete_surveys

Revision ID: 7917158dfb99
Revises: d4c4d64e643e
Create Date: 2025-11-15 13:53:11.611379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7917158dfb99'
down_revision: Union[str, None] = 'd4c4d64e643e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_trackers', 'question_variation_mapping')
    op.add_column('incomplete_surveys', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('incomplete_surveys', sa.Column('company_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_incomplete_surveys_company_url'), 'incomplete_surveys', ['company_url'], unique=False)
    op.create_foreign_key(None, 'incomplete_surveys', 'company_trackers', ['company_id'], ['id'])
    op.alter_column('question_variations', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('variation_sets', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('variation_sets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('variation_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('variation_sets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_variation_sets_id'), 'variation_sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variation_sets_id'), table_name='variation_sets')
    op.alter_column('variation_sets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('variation_sets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('variation_sets', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('variation_sets', 'is_template',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('question_variations', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'incomplete_surveys', type_='foreignkey')
    op.drop_index(op.f('ix_incomplete_surveys_company_url'), table_name='incomplete_surveys')
    op.drop_column('incomplete_surveys', 'company_url')
    op.drop_column('incomplete_surveys', 'company_id')
    op.add_column('company_trackers', sa.Column('question_variation_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON mapping of question IDs to variation IDs. Example: {"fc_q3": 123, "fc_q11": 456}. NULL or {} means use default questions.'))
    # ### end Alembic commands ###
