"""add_company_question_sets_table

Revision ID: c483380ec75e
Revises: 3b1ff4bac719
Create Date: 2025-10-04 13:56:24.496699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c483380ec75e'
down_revision: Union[str, None] = '3b1ff4bac719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_tracker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_questions', sa.JSON(), nullable=False),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.Column('excluded_questions', sa.JSON(), nullable=True),
    sa.Column('question_variations', sa.JSON(), nullable=True),
    sa.Column('demographic_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_tracker_id'], ['company_trackers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_question_sets_company_tracker_id'), 'company_question_sets', ['company_tracker_id'], unique=False)
    op.create_index(op.f('ix_company_question_sets_id'), 'company_question_sets', ['id'], unique=False)
    op.create_index(op.f('ix_company_question_sets_is_active'), 'company_question_sets', ['is_active'], unique=False)
    op.alter_column('customer_profiles', 'preferred_communication',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'email'::character varying"))
    op.alter_column('customer_profiles', 'islamic_finance_preference',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_customer_profiles_demographics', table_name='customer_profiles')
    op.create_index(op.f('ix_customer_profiles_age'), 'customer_profiles', ['age'], unique=False)
    op.create_index(op.f('ix_customer_profiles_emirate'), 'customer_profiles', ['emirate'], unique=False)
    op.create_index(op.f('ix_customer_profiles_nationality'), 'customer_profiles', ['nationality'], unique=False)
    op.alter_column('survey_responses', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('survey_responses', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('survey_responses', 'pdf_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('survey_responses', 'report_downloads',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_survey_responses_company', table_name='survey_responses')
    op.drop_index('idx_survey_responses_language', table_name='survey_responses')
    op.create_index(op.f('ix_survey_responses_company_tracker_id'), 'survey_responses', ['company_tracker_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_language'), 'survey_responses', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_language'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_company_tracker_id'), table_name='survey_responses')
    op.create_index('idx_survey_responses_language', 'survey_responses', ['language'], unique=False)
    op.create_index('idx_survey_responses_company', 'survey_responses', ['company_tracker_id', 'created_at'], unique=False)
    op.alter_column('survey_responses', 'report_downloads',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('survey_responses', 'pdf_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('survey_responses', 'email_sent',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('survey_responses', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_index(op.f('ix_customer_profiles_nationality'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_emirate'), table_name='customer_profiles')
    op.drop_index(op.f('ix_customer_profiles_age'), table_name='customer_profiles')
    op.create_index('idx_customer_profiles_demographics', 'customer_profiles', ['nationality', 'emirate', 'age'], unique=False)
    op.alter_column('customer_profiles', 'islamic_finance_preference',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('customer_profiles', 'preferred_communication',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    op.drop_index(op.f('ix_company_question_sets_is_active'), table_name='company_question_sets')
    op.drop_index(op.f('ix_company_question_sets_id'), table_name='company_question_sets')
    op.drop_index(op.f('ix_company_question_sets_company_tracker_id'), table_name='company_question_sets')
    op.drop_table('company_question_sets')
    # ### end Alembic commands ###
