"""add_financial_clinic_profile_and_response_tables

Revision ID: 69d35e0766b1
Revises: 001b495bba1c
Create Date: 2025-10-16 01:32:41.326090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d35e0766b1'
down_revision: Union[str, None] = '001b495bba1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create financial_clinic_responses table before any migration that alters it
    op.create_table(
        'financial_clinic_responses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('response_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_profiles_date_of_birth'), table_name='customer_profiles')
    op.drop_column('customer_profiles', 'income_range')
    op.drop_column('customer_profiles', 'date_of_birth')
    op.drop_index(op.f('ix_survey_responses_survey_version'), table_name='survey_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_survey_responses_survey_version'), 'survey_responses', ['survey_version'], unique=False)
    op.add_column('customer_profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('customer_profiles', sa.Column('income_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_customer_profiles_date_of_birth'), 'customer_profiles', ['date_of_birth'], unique=False)
    # ### end Alembic commands ###
