"""Add incomplete survey tracking

Revision ID: 240c9283bdec
Revises: 79b2254e8076
Create Date: 2025-10-02 18:32:10.247783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240c9283bdec'
down_revision: Union[str, None] = '79b2254e8076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomplete_surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_profile_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_abandoned', sa.Boolean(), nullable=True),
    sa.Column('follow_up_sent', sa.Boolean(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_profile_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incomplete_surveys_id'), 'incomplete_surveys', ['id'], unique=False)
    op.create_index(op.f('ix_incomplete_surveys_session_id'), 'incomplete_surveys', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incomplete_surveys_session_id'), table_name='incomplete_surveys')
    op.drop_index(op.f('ix_incomplete_surveys_id'), table_name='incomplete_surveys')
    op.drop_table('incomplete_surveys')
    # ### end Alembic commands ###
