"""add_is_active_to_company_details

Revision ID: a31796ca638c
Revises: 59b150ababb0
Create Date: 2025-12-30 18:39:51.709307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a31796ca638c'
down_revision: Union[str, None] = '59b150ababb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    
    # Add is_active column as nullable first
    op.add_column('company_details', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Update existing records to set is_active = True
    op.execute("UPDATE company_details SET is_active = True WHERE is_active IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('company_details', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_details', 'is_active')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
