"""resync migrations and add crm_api_keys

Revision ID: e4a5b59d6cb6
Revises: 1a05d3369003
Create Date: 2026-02-26 16:25:04.978118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a5b59d6cb6'
down_revision: Union[str, None] = '1a05d3369003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unsubscribed_users_email', table_name='unsubscribed_users')
    op.drop_index('ix_unsubscribed_users_id', table_name='unsubscribed_users')
    op.drop_table('unsubscribed_users')
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.drop_index('ix_email_automation_config_id', table_name='email_automation_config')
    op.drop_table('email_automation_config')
    op.drop_column('financial_clinic_profiles', 'last_reminder_at')
    op.drop_column('financial_clinic_profiles', 'reminder_sent_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_clinic_profiles', sa.Column('reminder_sent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('financial_clinic_profiles', sa.Column('last_reminder_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('email_automation_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('incomplete_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('incomplete_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('checkup_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checkup_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('incomplete_subject_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incomplete_subject_ar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incomplete_body_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incomplete_body_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkup_subject_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkup_subject_ar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkup_body_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkup_body_ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allowed_emails', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('incomplete_exclude_company_url', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('checkup_exclude_company_url', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_automation_config_pkey')
    )
    op.create_index('ix_email_automation_config_id', 'email_automation_config', ['id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.create_table('unsubscribed_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unsubscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='unsubscribed_users_pkey')
    )
    op.create_index('ix_unsubscribed_users_id', 'unsubscribed_users', ['id'], unique=False)
    op.create_index('ix_unsubscribed_users_email', 'unsubscribed_users', ['email'], unique=False)
    # ### end Alembic commands ###
