"""Add company_details_id column to financial_clinic_profiles

Revision ID: 2026_01_06_1430_123456789abc
Revises: 0188113496ea
Create Date: 2026-01-06 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '2026_01_06_1430_123456789abc'
down_revision: Union[str, None] = '0188113496ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [c['name'] for c in inspector.get_columns(table_name)]
    return column_name in columns


def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def constraint_exists(table_name, constraint_name):
    """Check if a foreign key constraint exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
    return constraint_name in fks


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add company_details_id column to financial_clinic_profiles only if it doesn't exist
    if not column_exists('financial_clinic_profiles', 'company_details_id'):
        op.add_column('financial_clinic_profiles', sa.Column('company_details_id', sa.Integer(), nullable=True))
    
    if not index_exists('financial_clinic_profiles', 'ix_financial_clinic_profiles_company_details_id'):
        op.create_index('ix_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', ['company_details_id'], unique=False)
    
    if not constraint_exists('financial_clinic_profiles', 'fk_financial_clinic_profiles_company_details_id'):
        op.create_foreign_key('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', 'company_details', ['company_details_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if constraint_exists('financial_clinic_profiles', 'fk_financial_clinic_profiles_company_details_id'):
        op.drop_constraint('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', type_='foreignkey')
    
    if index_exists('financial_clinic_profiles', 'ix_financial_clinic_profiles_company_details_id'):
        op.drop_index('ix_financial_clinic_profiles_company_details_id', table_name='financial_clinic_profiles')
    
    if column_exists('financial_clinic_profiles', 'company_details_id'):
        op.drop_column('financial_clinic_profiles', 'company_details_id')
    # ### end Alembic commands ###
