"""add unique constraint to company_details.company_name

Revision ID: aabcd0ff149b
Revises: 32a30a70da9e
Create Date: 2026-01-05 15:40:05.404207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'aabcd0ff149b'
down_revision: Union[str, None] = '32a30a70da9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def table_exists(table_name):
    """Check if a table exists."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop apscheduler_jobs if it exists
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # Update company_details index to be unique
    if table_exists('company_details'):
        if index_exists('company_details', 'ix_company_details_company_name'):
            op.drop_index('ix_company_details_company_name', table_name='company_details')
        op.create_index(op.f('ix_company_details_company_name'), 'company_details', ['company_name'], unique=True)
    
    # Update company_trackers
    if table_exists('company_trackers') and column_exists('company_trackers', 'enable_variations'):
        op.alter_column('company_trackers', 'enable_variations',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
    
    # Add company_name to financial_clinic_profiles
    if table_exists('financial_clinic_profiles'):
        if not column_exists('financial_clinic_profiles', 'company_name'):
            op.add_column('financial_clinic_profiles', sa.Column('company_name', sa.String(length=200), nullable=True))
        if not index_exists('financial_clinic_profiles', 'ix_financial_clinic_profiles_company_name'):
            op.create_index(op.f('ix_financial_clinic_profiles_company_name'), 'financial_clinic_profiles', ['company_name'], unique=False)
    
    # Update users admin_role
    if table_exists('users') and column_exists('users', 'admin_role'):
        op.alter_column('users', 'admin_role',
                   existing_type=sa.VARCHAR(length=50),
                   type_=sa.String(length=20),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin_role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_financial_clinic_profiles_company_name'), table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_name')
    op.alter_column('company_trackers', 'enable_variations',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_company_details_company_name'), table_name='company_details')
    op.create_index('ix_company_details_company_name', 'company_details', ['company_name'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
