"""Add company_details_id column to financial_clinic_profiles

Revision ID: 2026_01_06_1430_123456789abc
Revises: 0188113496ea
Create Date: 2026-01-06 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_01_06_1430_123456789abc'
down_revision: Union[str, None] = '0188113496ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add company_details_id column to financial_clinic_profiles
    op.add_column('financial_clinic_profiles', sa.Column('company_details_id', sa.Integer(), nullable=True))
    op.create_index('ix_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', ['company_details_id'], unique=False)
    op.create_foreign_key('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', 'company_details', ['company_details_id'], ['id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', type_='foreignkey')
    op.drop_index('ix_financial_clinic_profiles_company_details_id', table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_details_id')
    # ### end Alembic commands ###
