"""Add company_name column to financial_clinic_profiles

Revision ID: 0188113496ea
Revises: 50642fd6ec4c
Create Date: 2026-01-06 14:14:24.229631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0188113496ea'
down_revision: Union[str, None] = '50642fd6ec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    
    # Add company_name column to financial_clinic_profiles
    op.add_column('financial_clinic_profiles', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.create_index('ix_financial_clinic_profiles_company_name', 'financial_clinic_profiles', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_financial_clinic_profiles_company_name', table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_name')
    
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
