"""Add company_details_id to financial_clinic_profiles

Revision ID: 28efd6746a4f
Revises: aabcd0ff149b
Create Date: 2026-01-05 17:19:45.356268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28efd6746a4f'
down_revision: Union[str, None] = 'aabcd0ff149b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('financial_clinic_profiles', sa.Column('company_details_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_financial_clinic_profiles_company_details_id'), 'financial_clinic_profiles', ['company_details_id'], unique=False)
    op.create_foreign_key(None, 'financial_clinic_profiles', 'company_details', ['company_details_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_clinic_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_financial_clinic_profiles_company_details_id'), table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_details_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
