"""resync migrations and add crm_api_keys

Revision ID: e4a5b59d6cb6
Revises: 1a05d3369003
Create Date: 2026-02-26 16:25:04.978118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a5b59d6cb6'
down_revision: Union[str, None] = '1a05d3369003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_api_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('masked_key', sa.String(length=50), nullable=False),
        sa.Column('hashed_key', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_api_keys_hashed_key'), 'crm_api_keys', ['hashed_key'], unique=False)
    op.create_index(op.f('ix_crm_api_keys_id'), 'crm_api_keys', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_api_keys_id'), table_name='crm_api_keys')
    op.drop_index(op.f('ix_crm_api_keys_hashed_key'), table_name='crm_api_keys')
    op.drop_table('crm_api_keys')
    # ### end Alembic commands ###
