"""add email automation config and profile tracking

Revision ID: 3c58242e993f
Revises: 1a05d3369003
Create Date: 2026-02-19 01:37:18.199929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c58242e993f'
down_revision: Union[str, None] = '1a05d3369003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_automation_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incomplete_enabled', sa.Boolean(), nullable=False),
    sa.Column('incomplete_days', sa.Integer(), nullable=False),
    sa.Column('checkup_enabled', sa.Boolean(), nullable=False),
    sa.Column('checkup_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_automation_config_id'), 'email_automation_config', ['id'], unique=False)
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.create_index('idx_consultation_survey_response', 'consultation_requests', ['survey_response_id'], unique=False)
    op.create_index(op.f('ix_consultation_requests_survey_response_id'), 'consultation_requests', ['survey_response_id'], unique=False)
    op.add_column('financial_clinic_profiles', sa.Column('reminder_sent_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('financial_clinic_profiles', sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_clinic_profiles', 'last_reminder_at')
    op.drop_column('financial_clinic_profiles', 'reminder_sent_count')
    op.drop_index(op.f('ix_consultation_requests_survey_response_id'), table_name='consultation_requests')
    op.drop_index('idx_consultation_survey_response', table_name='consultation_requests')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_index(op.f('ix_email_automation_config_id'), table_name='email_automation_config')
    op.drop_table('email_automation_config')
    # ### end Alembic commands ###
