"""Add company_name column to financial_clinic_profiles

Revision ID: 0188113496ea
Revises: 50642fd6ec4c
Create Date: 2026-01-06 14:14:24.229631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '0188113496ea'
down_revision: Union[str, None] = '50642fd6ec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes


def table_exists(table_name):
    """Check if a table exists."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def constraint_exists(table_name, constraint_name):
    """Check if a foreign key constraint exists on a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    foreign_keys = inspector.get_foreign_keys(table_name)
    return any(fk['name'] == constraint_name for fk in foreign_keys)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Safely drop apscheduler_jobs table if it exists
    if table_exists('apscheduler_jobs'):
        if index_exists('apscheduler_jobs', 'ix_apscheduler_jobs_next_run_time'):
            op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')
    
    # Add company_name column to financial_clinic_profiles if it doesn't exist
    if not column_exists('financial_clinic_profiles', 'company_name'):
        op.add_column('financial_clinic_profiles', sa.Column('company_name', sa.String(length=200), nullable=True))
    
    if not index_exists('financial_clinic_profiles', 'ix_financial_clinic_profiles_company_name'):
        op.create_index('ix_financial_clinic_profiles_company_name', 'financial_clinic_profiles', ['company_name'], unique=False)
    
    # Add company_details_id column to financial_clinic_profiles if it doesn't exist
    if not column_exists('financial_clinic_profiles', 'company_details_id'):
        op.add_column('financial_clinic_profiles', sa.Column('company_details_id', sa.Integer(), nullable=True))
    
    if not index_exists('financial_clinic_profiles', 'ix_financial_clinic_profiles_company_details_id'):
        op.create_index('ix_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', ['company_details_id'], unique=False)
    
    if not constraint_exists('financial_clinic_profiles', 'fk_financial_clinic_profiles_company_details_id'):
        op.create_foreign_key('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', 'company_details', ['company_details_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_financial_clinic_profiles_company_details_id', 'financial_clinic_profiles', type_='foreignkey')
    op.drop_index('ix_financial_clinic_profiles_company_details_id', table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_details_id')
    
    op.drop_index('ix_financial_clinic_profiles_company_name', table_name='financial_clinic_profiles')
    op.drop_column('financial_clinic_profiles', 'company_name')
    
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
