"""add_company_url_exclusion_toggles

Revision ID: 702b4b28dfa0
Revises: 04589832f0d3
Create Date: 2026-02-25 16:31:52.579328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '702b4b28dfa0'
down_revision: Union[str, None] = '04589832f0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs', if_exists=True)
    op.drop_table('apscheduler_jobs', if_exists=True)
    op.add_column('email_automation_config', sa.Column(
        'incomplete_exclude_company_url', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('email_automation_config', sa.Column(
        'checkup_exclude_company_url', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_automation_config', 'checkup_exclude_company_url')
    op.drop_column('email_automation_config', 'incomplete_exclude_company_url')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
